apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: assignment3
data:
  db_host: mysql
  db_name: flaskdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: assignment3
data:
  nginx.conf: |
    server {
        listen 80;
        location / {
            proxy_pass http://flask-service:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
