apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: assignment3
type: Opaque
stringData:
  mysql_root_password: rootpass
  mysql_database: flaskdb
  mysql_user: flaskuser
  mysql_password: flaskpass
